### ISSUE TITLE
虚拟列表好像不好使

### ISSUE THREAD

**Issue by windyoung1990** [raohong/taro-list#12]
![image](https://user-images.githubusercontent.com/21021859/87513946-13f94800-c6ac-11ea-808a-52d4d84ff753.png)
![image](https://user-images.githubusercontent.com/21021859/87514135-56228980-c6ac-11ea-93bb-0ca30888667e.png)
![Uploading image.png…]()
dom中还是一次性加载了所有list数据，请大神帮忙看下

**Comment by raohong** [comment]
参考 https://github.com/raohong/taro-list-demo/blob/master/src/pages/list/index.tsx

不支持 3.0

**Comment by windyoung1990** [comment]
> 参考 https://github.com/raohong/taro-list-demo/blob/master/src/pages/list/index.tsx
> 
> 不支持 3.0
版本是2.2.6  我这边做的是百度小程序，会有影响么

**Comment by windyoung1990** [comment]
> 参考 https://github.com/raohong/taro-list-demo/blob/master/src/pages/list/index.tsx
> 
> 不支持 3.0
参考了 还是不行 不触发onVirtualListInit的回调
代码感觉写的没啥问题呢

import Taro, { Component, Config } from '@tarojs/taro'
import { View, Image, ScrollView } from '@tarojs/components'
import { kACGImageSizeFormat } from '../../common/tools/tools'
import {
  VirtualListDataManager,
  VirtualListItemData
} from 'taro-list-data-manager';
import TaroList from 'taro-list'
import EpisodeList from './episodelist'
import './columnepisode.scss'
const app = Taro.getApp()
const Threshold = 20

class ColumnEpisode extends Component<any, any> {
  constructor(props) {
    super(props)
    this.state = {
      list: []
    }
  }
  dataManager = new VirtualListDataManager(
    {
      itemSize: '100px',
      overscan: 2,
      // estimatedSize 尽可能接近真实尺寸
      estimatedSize: 70,
      onChange: data => {
        this.setState({
          list: data
        });
      }
    },
    Taro
  );
  loadStatus = 'none';

  static defaultProps = {
    isShow: false,
    dataList: [],
    defaultPic: '',
    updateScheduleTitle: '',
    serializeStatus: 1,
  }
  handleInit = () => {
    debugger
    this.dataManager.clearAllLoadStatus();
      this.dataManager.updateConfig({
        itemSize: '100px'
      });
    console.log('init handle')
    const { dataList = [] } = this.props
    console.log(dataList,";dataList")
    this.dataManager.set(dataList);
  }
  


  /**
   * 关闭隐藏弹出的竖排目录列表
   */
  clickHideColumnEpisode = (e) => {
    e.stopPropagation()
    this.props.changeShow(false)
  }
  render () {
    const {list } = this.state;
    console.log(list,'1212')
    return (
        <View className='columnepisode-container'>
          <TaroList
            className='columnepisode-body'
            onVirtualListInit={this.handleInit}
            virtual
            height='66vh'
            dataManager={this.dataManager}
          >
            {
              list.map((item, index) => (
                <EpisodeList
                  key={'episodelist' + index}
                  episodeInfo={item}
                  episodesIndex={index === this.state.episodesIndex ? 'active' : ''}
                ></EpisodeList>
              ))
            }
          </TaroList>
        </View>
    )
  }
}
export default ColumnEpisode

**Comment by windyoung1990** [comment]
编译成微信小程序，确实会执行onVirtualListInit的回调，百度小程序不行

**Comment by raohong** [comment]
只支持网页 和微信小程序

**Comment by windyoung1990** [comment]
> 只支持网页 和微信小程序

好吧 冒昧的问下，兼容百度小程序的话，麻烦么，感谢回复

**Comment by raohong** [comment]
主要是兼容了 刷新. 微信使用了 wxs.
目前没有该计划
